features_information:

  UserID             :   object
  ItemID             :   object
  Rating             :   int64
  PurchaseHistory    :   object
  CartActivity       :   object
  WishlistActivity   :   object
  Clicks             :   int64
  Views              :   int64
  TimeSpentOnItem    :   float64
  PurchaseDate       :   datetime64[ns]
  SessionDuration    :   float64
  DeviceType         :   object
  AbandonedCartData  :   object
  Age                :   int64
  Gender             :   object
  Location           :   object
  Income             :   object
  Occupation         :   object
  SignUpDate         :   datetime64[ns]
  MembershipLevel    :   object
  BrowsingHistory    :   object
  Device             :   object
  TimeOfInteraction  :   object
  SearchQueries      :   object
  ProductName        :   object
  Category           :   object
  Price              :   float64
  Discount           :   float64
  Brand              :   object
  Description        :   object
  Tags               :   object
  Color              :   object
  Size               :   object
  Stock              :   int64
  Ratings            :   float64
  Reviews            :   object
  ReleaseDate        :   datetime64[ns]
  PopularityScore    :   git float64
  
target_columns:

  target_column1:UserID
  target_column2:ItemID
  target_column3:Ratings
  